// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozzIQvwmEFjo3JREzo-iTLyfSWBc2LfI',
    appId: '1:976464516308:web:dca396763cd33cc511d741',
    messagingSenderId: '976464516308',
    projectId: 'appfinal-69723',
    authDomain: 'appfinal-69723.firebaseapp.com',
    storageBucket: 'appfinal-69723.appspot.com',
    measurementId: 'G-1P4VECKQ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcouSiHAs7oJTUHZfUePfKoyMg4GPpfI',
    appId: '1:976464516308:android:b791e0fca83b32ed11d741',
    messagingSenderId: '976464516308',
    projectId: 'appfinal-69723',
    storageBucket: 'appfinal-69723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhB3GzF0CPjX9UVxFIuP8IcyOX-Ptdq4w',
    appId: '1:976464516308:ios:891a4fedca3314a011d741',
    messagingSenderId: '976464516308',
    projectId: 'appfinal-69723',
    storageBucket: 'appfinal-69723.appspot.com',
    iosClientId: '976464516308-6qm7e9tn0hqts6p3r1l2l446dg21lfca.apps.googleusercontent.com',
    iosBundleId: 'com.SanFer.proyectofinal',
  );
}
